# Generated by Django 3.1.7 on 2021-05-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='passwordagain',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
